services:
  - type: web
    name: l43shoon-afrad
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOCAL_SESSION_SECRET
        generateValue: true
      - key: SQL_HOST
        fromDatabase:
          name: l43shoon-afrad-db
          property: host
      - key: SQL_DB_NAME
        fromDatabase:
          name: l43shoon-afrad-db
          property: database
      - key: SQL_USER
        fromDatabase:
          name: l43shoon-afrad-db
          property: user
      - key: SQL_PASSWORD
        fromDatabase:
          name: l43shoon-afrad-db
          property: password
      - key: SQL_ADMIN_USER
        fromDatabase:
          name: l43shoon-afrad-db
          property: user
      - key: SQL_ADMIN_PASSWORD
        fromDatabase:
          name: l43shoon-afrad-db
          property: password

databases:
  - name: l43shoon-afrad-db
    plan: free
    databaseName: l43shoon_afrad
    user: l43shoon_user
